// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: aruku.proto

#include "aruku.pb.h"
#include "aruku.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace ros2_ws {
namespace aruku {
namespace proto {

static const char* Config_method_names[] = {
  "/ros2_ws.aruku.proto.Config/GetConfig",
  "/ros2_ws.aruku.proto.Config/SaveConfig",
};

std::unique_ptr< Config::Stub> Config::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Config::Stub> stub(new Config::Stub(channel, options));
  return stub;
}

Config::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_GetConfig_(Config_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SaveConfig_(Config_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Config::Stub::GetConfig(::grpc::ClientContext* context, const ::ros2_ws::aruku::proto::Empty& request, ::ros2_ws::aruku::proto::ConfigWalking* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ros2_ws::aruku::proto::Empty, ::ros2_ws::aruku::proto::ConfigWalking, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetConfig_, context, request, response);
}

void Config::Stub::async::GetConfig(::grpc::ClientContext* context, const ::ros2_ws::aruku::proto::Empty* request, ::ros2_ws::aruku::proto::ConfigWalking* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ros2_ws::aruku::proto::Empty, ::ros2_ws::aruku::proto::ConfigWalking, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetConfig_, context, request, response, std::move(f));
}

void Config::Stub::async::GetConfig(::grpc::ClientContext* context, const ::ros2_ws::aruku::proto::Empty* request, ::ros2_ws::aruku::proto::ConfigWalking* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetConfig_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ros2_ws::aruku::proto::ConfigWalking>* Config::Stub::PrepareAsyncGetConfigRaw(::grpc::ClientContext* context, const ::ros2_ws::aruku::proto::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ros2_ws::aruku::proto::ConfigWalking, ::ros2_ws::aruku::proto::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetConfig_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ros2_ws::aruku::proto::ConfigWalking>* Config::Stub::AsyncGetConfigRaw(::grpc::ClientContext* context, const ::ros2_ws::aruku::proto::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetConfigRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Config::Stub::SaveConfig(::grpc::ClientContext* context, const ::ros2_ws::aruku::proto::ConfigWalking& request, ::ros2_ws::aruku::proto::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ros2_ws::aruku::proto::ConfigWalking, ::ros2_ws::aruku::proto::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SaveConfig_, context, request, response);
}

void Config::Stub::async::SaveConfig(::grpc::ClientContext* context, const ::ros2_ws::aruku::proto::ConfigWalking* request, ::ros2_ws::aruku::proto::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ros2_ws::aruku::proto::ConfigWalking, ::ros2_ws::aruku::proto::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SaveConfig_, context, request, response, std::move(f));
}

void Config::Stub::async::SaveConfig(::grpc::ClientContext* context, const ::ros2_ws::aruku::proto::ConfigWalking* request, ::ros2_ws::aruku::proto::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SaveConfig_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ros2_ws::aruku::proto::Empty>* Config::Stub::PrepareAsyncSaveConfigRaw(::grpc::ClientContext* context, const ::ros2_ws::aruku::proto::ConfigWalking& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ros2_ws::aruku::proto::Empty, ::ros2_ws::aruku::proto::ConfigWalking, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SaveConfig_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ros2_ws::aruku::proto::Empty>* Config::Stub::AsyncSaveConfigRaw(::grpc::ClientContext* context, const ::ros2_ws::aruku::proto::ConfigWalking& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSaveConfigRaw(context, request, cq);
  result->StartCall();
  return result;
}

Config::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Config_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Config::Service, ::ros2_ws::aruku::proto::Empty, ::ros2_ws::aruku::proto::ConfigWalking, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Config::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ros2_ws::aruku::proto::Empty* req,
             ::ros2_ws::aruku::proto::ConfigWalking* resp) {
               return service->GetConfig(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Config_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Config::Service, ::ros2_ws::aruku::proto::ConfigWalking, ::ros2_ws::aruku::proto::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Config::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ros2_ws::aruku::proto::ConfigWalking* req,
             ::ros2_ws::aruku::proto::Empty* resp) {
               return service->SaveConfig(ctx, req, resp);
             }, this)));
}

Config::Service::~Service() {
}

::grpc::Status Config::Service::GetConfig(::grpc::ServerContext* context, const ::ros2_ws::aruku::proto::Empty* request, ::ros2_ws::aruku::proto::ConfigWalking* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Config::Service::SaveConfig(::grpc::ServerContext* context, const ::ros2_ws::aruku::proto::ConfigWalking* request, ::ros2_ws::aruku::proto::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace ros2_ws
}  // namespace aruku
}  // namespace proto

