name: Build and Test Nightly
on:
  workflow_dispatch:
  pull_request:
    branches: [master]
  push:
    branches: [master]
jobs:
  build-and-test-nightly:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2.3.4
        with:
          path: aruku

      - name: Add nightly Debian repository and rosdep sources list
        run: |
          sudo apt update && sudo apt install curl
          curl -s ${{ secrets.SERVER_BASE_URL }}/debian/setup-nightly.bash | bash -s
          curl -s ${{ secrets.SERVER_BASE_URL }}/rosdep/setup.bash | bash -s

      - name: Build and test workspace
        uses: ichiro-its/ros2-build-and-test-action@main
