name: Build and Test
on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out
        uses: actions/checkout@v2.3.4
      - name: Build and test workspace
        uses: ichiro-its/ros2-ci@master
        with:
          ros2-distro: foxy
          pre-install: curl -s http://repository.ichiro-its.org/debian/setup-nightly.bash | bash -s
          apt-packages: ros-foxy-framework-common ros-foxy-framework-math
          pre-build: git clone https://github.com/ichiro-its/tachimawari /ws/tachimawari
